name: CiFuzz

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check repo.
      uses: actions/checkout@v4

    - name: Init image
      run: ./name.sh

    - name: Build image
      run: ./build.sh

    - name: run fuzzer
      run: ./run.sh
